# Generated by Django 5.2.5 on 2025-08-27 13:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_listing_image_2_listing_image_3_listing_image_4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('full_refund_days', models.PositiveIntegerField(default=7, help_text='Days before start for full refund')),
                ('partial_refund_days', models.PositiveIntegerField(default=3, help_text='Days before start for partial refund')),
                ('partial_refund_percent', models.PositiveIntegerField(default=50, help_text='Percentage refund for partial refund period')),
                ('security_deposit_percent', models.PositiveIntegerField(default=0, help_text='Security deposit as percentage of reservation amount')),
                ('security_deposit_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed security deposit amount', max_digits=10)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('requires_verification', models.BooleanField(default=False, help_text='Require verified listing for this policy')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('property_condition', 'Property Condition'), ('no_show', 'No Show'), ('misrepresentation', 'Misrepresentation'), ('payment_issue', 'Payment Issue'), ('policy_violation', 'Policy Violation'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('awaiting_response', 'Awaiting Response'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_json', models.JSONField(default=dict, help_text='Evidence files, screenshots, messages, etc.')),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('opener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_type', models.CharField(choices=[('rental', 'Rental'), ('purchase', 'Purchase'), ('short_stay', 'Short Stay'), ('viewing_fee', 'Viewing Fee')], default='rental', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('escrow_state', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('released', 'Released'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('escrow_reference', models.CharField(blank=True, max_length=128)),
                ('policy', models.JSONField(default=dict, help_text='Cancellation policy, terms, and conditions')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
