# Generated by Django 5.2.5 on 2025-08-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='disputecase',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='bookings.reservation'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['buyer', 'escrow_state'], name='bookings_re_buyer_i_94823b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['listing', 'escrow_state'], name='bookings_re_listing_e9414c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['escrow_state', 'created_at'], name='bookings_re_escrow__c6c7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_at', 'end_at'], name='bookings_re_start_a_4d8942_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['reservation', 'status'], name='bookings_di_reserva_74143e_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['opener', 'status'], name='bookings_di_opener__0b42a2_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['assigned_to', 'status'], name='bookings_di_assigne_a566f4_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['status', 'priority'], name='bookings_di_status_f37e56_idx'),
        ),
    ]
