# Generated by Django 5.2.5 on 2025-08-27 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_listing_image_2_listing_image_3_listing_image_4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('listing', 'Listing Verification'), ('user', 'User Verification'), ('agency', 'Agency Verification')], max_length=20)),
                ('description', models.TextField()),
                ('required_documents', models.JSONField(default=list, help_text='List of required document types')),
                ('optional_documents', models.JSONField(default=list, help_text='List of optional document types')),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_approve_threshold', models.FloatField(blank=True, help_text='Auto-approve if confidence score >= this value', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('listing', 'Listing Verification'), ('user', 'User Verification'), ('agency', 'Agency Verification')], max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('needs_more_info', 'Needs More Info'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submission_notes', models.TextField(blank=True, help_text='Notes from the applicant')),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal notes from staff')),
                ('public_feedback', models.TextField(blank=True, help_text='Feedback shown to applicant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verification_cases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_cases', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('land_certificate', 'Land Certificate'), ('building_permit', 'Building Permit'), ('occupancy_certificate', 'Occupancy Certificate'), ('property_photos', 'Property Photos'), ('floor_plans', 'Floor Plans'), ('national_id', 'National ID'), ('passport', 'Passport'), ('business_license', 'Business License'), ('tax_certificate', 'Tax Certificate'), ('professional_license', 'Professional License'), ('other', 'Other Document')], max_length=30)),
                ('file', models.FileField(upload_to='verification_documents/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.verificationcase')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], max_length=20)),
                ('reason', models.TextField(help_text='Reason for the decision')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this verification expires (if applicable)', null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score (0.0-1.0) for automated decisions', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_decisions', to=settings.AUTH_USER_MODEL)),
                ('verification_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='verification.verificationcase')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['status', 'case_type'], name='verificatio_status_55f568_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['user', 'status'], name='verificatio_user_id_1169c2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['assigned_to', 'status'], name='verificatio_assigne_61c20d_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcase',
            index=models.Index(fields=['created_at'], name='verificatio_created_8dc80f_idx'),
        ),
    ]
