# Generated by Django 5.2.5 on 2025-08-27 13:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_listing_image_2_listing_image_3_listing_image_4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('matterport', 'Matterport'), ('zillow', 'Zillow 3D Home'), ('cupix', 'Cupix'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('custom', 'Custom/Self-hosted')], max_length=20)),
                ('kind', models.CharField(choices=[('3d', '3D Tour'), ('video', 'Video Tour'), ('360', '360° Photos'), ('vr', 'VR Experience')], max_length=10)),
                ('default_gated', models.BooleanField(default=False)),
                ('default_requirements', models.JSONField(blank=True, default=dict)),
                ('url_pattern', models.CharField(blank=True, help_text='URL pattern with placeholders like {tour_id}', max_length=500)),
                ('embed_pattern', models.CharField(blank=True, help_text='Embed URL pattern with placeholders', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('3d', '3D Tour'), ('video', 'Video Tour'), ('360', '360° Photos'), ('vr', 'VR Experience')], default='3d', max_length=10)),
                ('provider', models.CharField(choices=[('matterport', 'Matterport'), ('zillow', 'Zillow 3D Home'), ('cupix', 'Cupix'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('custom', 'Custom/Self-hosted')], default='custom', max_length=20)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('embed_url', models.URLField(blank=True, help_text='Embeddable URL if different from main URL')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_gated', models.BooleanField(default=False, help_text='Require special access to view this tour')),
                ('access_requirements', models.JSONField(blank=True, default=dict, help_text='Requirements for gated access (verified_user, paid_visit, etc.)')),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Tour duration in seconds', null=True)),
                ('file_size_mb', models.FloatField(blank=True, help_text='File size in MB for hosted content', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific metadata')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tours', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_assets', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('access_method', models.CharField(choices=[('direct', 'Direct Link'), ('embed', 'Embedded View'), ('api', 'API Access')], default='direct', max_length=20)),
                ('referrer_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Time spent viewing tour', null=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tour_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='tours.tourasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tourasset',
            index=models.Index(fields=['listing', 'is_active'], name='tours_toura_listing_33e05d_idx'),
        ),
        migrations.AddIndex(
            model_name='tourasset',
            index=models.Index(fields=['kind', 'provider'], name='tours_toura_kind_d7aa05_idx'),
        ),
        migrations.AddIndex(
            model_name='tourasset',
            index=models.Index(fields=['is_gated'], name='tours_toura_is_gate_2f7941_idx'),
        ),
        migrations.AddIndex(
            model_name='touraccesslog',
            index=models.Index(fields=['tour_asset', 'created_at'], name='tours_toura_tour_as_f7509e_idx'),
        ),
        migrations.AddIndex(
            model_name='touraccesslog',
            index=models.Index(fields=['user', 'created_at'], name='tours_toura_user_id_1ec0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='touraccesslog',
            index=models.Index(fields=['session_id', 'created_at'], name='tours_toura_session_cd28bd_idx'),
        ),
    ]
