# Generated by Django 5.2.5 on 2025-08-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("urban", "Urban"),
                            ("suburban", "Suburban"),
                            ("rural", "Rural"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("borough", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("condo", "Condo"),
                            ("townhouse", "Townhouse"),
                            ("land", "Land"),
                        ],
                        default="apartment",
                        max_length=50,
                    ),
                ),
                (
                    "property_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("pending", "Pending"),
                            ("rented", "Rented"),
                        ],
                        default="available",
                        max_length=50,
                    ),
                ),
                (
                    "rental_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("weekly", "Weekly"),
                            ("daily", "Daily"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("furnished", models.BooleanField(default=False)),
                ("pool", models.BooleanField(default=False)),
                ("parking", models.BooleanField(default=False)),
                ("cctv", models.BooleanField(default=False)),
                ("garden", models.BooleanField(default=False)),
                ("elevator", models.BooleanField(default=False)),
                ("bedrooms", models.PositiveIntegerField(default=0)),
                ("bathrooms", models.PositiveIntegerField(default=0)),
                (
                    "area_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date_available", models.DateField(blank=True, null=True)),
                ("agent_name", models.CharField(blank=True, max_length=100, null=True)),
                ("agent_phone", models.CharField(blank=True, max_length=15, null=True)),
                ("date_posted", models.DateField(auto_now_add=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
