# Generated by Django 5.2.5 on 2025-08-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listing_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image_main",
            field=models.ImageField(
                blank=True, null=True, upload_to="listing_images/%Y/%m/%d/"
            ),
        ),
    ]
