# Generated by Django 5.2.5 on 2025-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_image_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image_2",
            field=models.ImageField(
                blank=True, null=True, upload_to="listing_images/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="image_3",
            field=models.ImageField(
                blank=True, null=True, upload_to="listing_images/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="image_4",
            field=models.ImageField(
                blank=True, null=True, upload_to="listing_images/%Y/%m/%d/"
            ),
        ),
    ]
